"""
Django settings for giftme project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from decimal import Decimal
from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / ".env")
except ImportError:
    pass


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in ("1", "true", "yes")


def _env_list(name, default=""):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-!wqo72-*lsuvau8a#hgy_00_oacv+xz-+&hpyo9ae47s8dytsx",
)
DEBUG = _env_bool("DEBUG", True)

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", "localhost,127.0.0.1,.railway.app")
RAILWAY_PUBLIC_DOMAIN = os.environ.get("RAILWAY_PUBLIC_DOMAIN", "")
if RAILWAY_PUBLIC_DOMAIN and RAILWAY_PUBLIC_DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS")
if RAILWAY_PUBLIC_DOMAIN:
    railway_origin = f"https://{RAILWAY_PUBLIC_DOMAIN}"
    if railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(railway_origin)

# Production HTTPS hosts must be in CSRF_TRUSTED_ORIGINS or POSTs return HTML 403
# (signup AJAX then fails with "Unexpected token '<'").
_local_hosts = {"localhost", "127.0.0.1", "[::1]"}
for host in ALLOWED_HOSTS:
    if not host or host.startswith(".") or host in _local_hosts:
        continue
    origin = f"https://{host}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'birthdays.apps.BirthdaysConfig',
    'ops.apps.OpsConfig',
]

try:
    import whitenoise  # noqa: F401

    _HAS_WHITENOISE = True
except ImportError:
    _HAS_WHITENOISE = False

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]
if _HAS_WHITENOISE:
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')
MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'giftme.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ops.context_processors.ops_stats',
                'birthdays.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'giftme.wsgi.application'


# Database
# DEBUG=True  → SQLite (local)
# DEBUG=False → Postgres via DATABASE_URL
if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    database_url = os.environ.get("DATABASE_URL", "").strip()
    if not database_url:
        raise ImproperlyConfigured(
            "DEBUG is False but DATABASE_URL is not set. "
            "Add a Postgres connection string to your .env."
        )
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_LOGOUT_ON_GET = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[GiftMe] "
ACCOUNT_ADAPTER = "birthdays.adapters.AccountAdapter"

LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "home"

# M-Pesa Daraja (Lipa na M-Pesa)
MPESA_ENV = os.environ.get("MPESA_ENV", "sandbox")
MPESA_BASE_URL = os.environ.get(
    "MPESA_BASE_URL",
    "https://sandbox.safaricom.co.ke" if MPESA_ENV == "sandbox" else "https://api.safaricom.co.ke",
)
MPESA_CONSUMER_KEY = os.environ.get("MPESA_CONSUMER_KEY", "")
MPESA_CONSUMER_SECRET = os.environ.get("MPESA_CONSUMER_SECRET", "")
MPESA_SHORTCODE = os.environ.get("MPESA_SHORTCODE", "")
MPESA_PASSKEY = os.environ.get("MPESA_PASSKEY", "")
MPESA_CALLBACK_URL = os.environ.get("MPESA_CALLBACK_URL", "")
MPESA_TRANSACTION_TYPE = os.environ.get("MPESA_TRANSACTION_TYPE", "CustomerPayBillOnline")

# M-Pesa B2C (withdrawals)
MPESA_B2C_SHORTCODE = os.environ.get("MPESA_B2C_SHORTCODE", "")
MPESA_B2C_INITIATOR_NAME = os.environ.get("MPESA_B2C_INITIATOR_NAME", "")
MPESA_B2C_SECURITY_CREDENTIAL = os.environ.get("MPESA_B2C_SECURITY_CREDENTIAL", "")
MPESA_B2C_COMMAND_ID = os.environ.get("MPESA_B2C_COMMAND_ID", "BusinessPayment")
MPESA_B2C_RESULT_URL = os.environ.get("MPESA_B2C_RESULT_URL", "")
MPESA_B2C_TIMEOUT_URL = os.environ.get("MPESA_B2C_TIMEOUT_URL", "")

WITHDRAWAL_MIN_AMOUNT = 500
WITHDRAWAL_OTP_EXPIRY_MINUTES = int(os.environ.get("WITHDRAWAL_OTP_EXPIRY_MINUTES", "10"))

# Email (verification, password reset, withdrawal OTP)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = _env_bool("EMAIL_USE_TLS", True)
EMAIL_USE_SSL = _env_bool("EMAIL_USE_SSL", False)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "GiftMe <info@giftme.co.ke>")
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Prefer SMTP whenever a host is configured. Console backend only dumps to the terminal.
_email_backend = os.environ.get("EMAIL_BACKEND", "").strip()
if EMAIL_HOST and (
    not _email_backend
    or _email_backend.endswith("console.EmailBackend")
):
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
elif _email_backend:
    EMAIL_BACKEND = _email_backend
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Redis cache (optional — falls back to local memory)
# Ignore localhost Redis in production; Railway has no Redis on 127.0.0.1.
REDIS_URL = os.environ.get("REDIS_URL", "").strip()
_redis_is_local = REDIS_URL.startswith(("redis://127.0.0.1", "redis://localhost"))
if REDIS_URL and not (not DEBUG and _redis_is_local):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                "IGNORE_EXCEPTIONS": True,
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

STK_QUERY_MIN_AGE_SECONDS = int(os.environ.get("STK_QUERY_MIN_AGE_SECONDS", "25"))
STK_IP_LIMIT = int(os.environ.get("STK_IP_LIMIT", "10"))
STK_IP_WINDOW = int(os.environ.get("STK_IP_WINDOW", "60"))
STK_PHONE_LIMIT = int(os.environ.get("STK_PHONE_LIMIT", "5"))
STK_PHONE_WINDOW = int(os.environ.get("STK_PHONE_WINDOW", "3600"))
STK_MAX_PENDING_PER_PHONE_PROFILE = int(os.environ.get("STK_MAX_PENDING_PER_PHONE_PROFILE", "3"))
STK_PROFILE_LIMIT = int(os.environ.get("STK_PROFILE_LIMIT", "100"))
STK_PROFILE_WINDOW = int(os.environ.get("STK_PROFILE_WINDOW", "3600"))
PAYMENT_PENDING_EXPIRY_MINUTES = int(os.environ.get("PAYMENT_PENDING_EXPIRY_MINUTES", "15"))

PLATFORM_FEE_PERCENT = Decimal(os.environ.get("PLATFORM_FEE_PERCENT", "10"))
PLATFORM_FEE_CAP = Decimal(os.environ.get("PLATFORM_FEE_CAP", "800"))
