# Generated by Django 6.0.5 on 2026-06-02 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('age_turning', models.PositiveIntegerField()),
                ('birthday_date', models.DateField()),
                ('bio', models.TextField(blank=True)),
                ('cover_image_url', models.URLField(blank=True)),
                ('payout_phone', models.CharField(blank=True, max_length=20)),
                ('payout_wallet_name', models.CharField(blank=True, max_length=120)),
                ('goal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('icon', models.CharField(help_text='Font Awesome icon class, e.g. fa-cake-candles', max_length=40)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('animation', models.CharField(blank=True, default='', max_length=40)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_options', to='birthdays.birthdaypage')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'unique_together': {('page', 'label')},
            },
        ),
        migrations.CreateModel(
            name='GiftContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('message', models.CharField(blank=True, max_length=220)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='birthdays.birthdaypage')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='birthdays.giftoption')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
