# Generated by Django 6.0.5 on 2026-06-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0004_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='page',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gift_slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payout_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='birthdays.userprofile'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='birthdays.userprofile'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='birthdays.birthdaypage'),
        ),
        migrations.CreateModel(
            name='UserGiftReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('gift_label', models.CharField(default='Gift', max_length=120)),
                ('message', models.CharField(blank=True, max_length=220)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to='birthdays.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
