# Generated by Django 6.0.5 on 2026-06-02 22:20

import uuid

from django.db import migrations, models


def backfill_profile_uuids(apps, schema_editor):
    UserProfile = apps.get_model("birthdays", "UserProfile")
    used = set()

    def unique_uuid():
        while True:
            value = str(uuid.uuid4())
            if value not in used:
                used.add(value)
                return value

    for profile in UserProfile.objects.all():
        profile.gift_slug = unique_uuid()
        profile.wishlist_slug = unique_uuid()
        profile.save(update_fields=["gift_slug", "wishlist_slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0005_remove_wishlistitem_page_userprofile_gift_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wishlist_slug',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gift_slug',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
        migrations.RunPython(backfill_profile_uuids, migrations.RunPython.noop),
    ]
