# Generated by Django 6.0.5 on 2026-06-03 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0007_catalog_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergiftreceived',
            name='payer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='usergiftreceived',
            name='wishlist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='birthdays.wishlistitem'),
        ),
    ]
