# Generated by Django 6.0.5 on 2026-06-03 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0008_gift_contribution_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=120)),
                ('payer_phone', models.CharField(max_length=20)),
                ('message', models.CharField(blank=True, max_length=220)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gift_label', models.CharField(default='Gift', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('account_reference', models.CharField(max_length=12, unique=True)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('merchant_request_id', models.CharField(blank=True, max_length=64)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=32)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog_gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='birthdays.cataloggift')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payments', to='birthdays.userprofile')),
                ('wishlist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='birthdays.wishlistitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usergiftreceived',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_record', to='birthdays.mpesapayment'),
        ),
    ]
