# Generated by Django 6.0.6 on 2026-07-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0010_withdrawal_b2c_otp'),
        ('birthdays', '0012_sitesettings_website_url'),
    ]

    operations = [
    ]
